language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: noels@silex-consulting.com
  api_key:
    secure: TIITtRW3qz8k0K+Me9ztovesMasSTHywmbu6Sg7Or6QUjD6svuYmd4Y1EfBPrGOBpJ1WftQ6t9enDRayE7RA6pFA1kD/BbYv/EwXm2ezpUyozJc/8VhZ4qXNcaXYdrwriOjGOy6x+45ATo4sKJ31vVSfufDm3on3z+sXj3DH4QsKGmh5nhU5ekOdJC7J4ltLUbBHrv3afhnnpYYuldGoT83uWUwgIQ1KHhDM+5Dh4bDhvfaT0XTbm/ZTF6Zk44vMgafjf33M42yXaeyyzjJI4n+qJzUrrNHa4tNqJxTJ0oFQnVFnDXRRIOA/zQJ63uxpF2Yn5NI17Jk1oRO6z7pYE3+GSaKARuiqng2KOKl9+BwEX6C4SYdt4APE25cnRDZKDDd5xOh+IBjSt/PjkD6jcO8r51sa/njricjPEdEZS3ImECJYBFy2NwyR0aFOgTREr/5jXnjY1Veuk7KpqDKf44iqogssvAoI8g+M4f3h95NpTuxhOECsSPuA/XPBTmO5xlM0Y5DcP9PX4ytV23YNYZGtbFnj/sFYxGFEfu+34uW/zz4X4uLRdvoJBNJGIy/15eLt8op0Id6eUhtPYeAQXQunmxq1eQwvfZ4jAYpRXDwKmocYimgFXrQK6RO4BB2s48qjwZChlQV6hJOCJH7eki20mUflMCpcxOmDpxgEyV4=
  on:
    tags: true
    repo: UKHomeOffice/eslint-config-homeoffice
